[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
[build.environment]
  YARN_VERSION = "1.22.5"

[dev]
  framework = "#auto"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "netlify-plugin-image-optim"
