[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
[build.environment]
  YARN_VERSION = "1.22.5"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects NextJS and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
