module.exports = [
  'is a web developer',
  'writes code',
  'is on GitHub',
  'drives an Asp Explorer',
  'likes racing cars',
  'is online',
  'is offline',
  'is typing',
  "doesn't smoke",
  'plays video games',
  'is hyped for Ace Combat 7',
  'has a phone',
  'takes photos',
  'has a Raspberry Pi',
  'is afraid of dogs',
  'hates TV',
  'likes dank memes (and code)',
  'likes vaporwave',
  'does React',
  'does TypeScript',
  'does JavaScript',
  'does Elixir',
  'does Laravel',
  'does node.js',
  'listens to music',
  'has a laptop',
  'wrote this flavor text',
  'has internet',
  'sleeps at night',
  'is not a furry',
  'wishes you a good day',
  'probably likes you',
  "thinks you're cool"
]
