module.exports = [
  'is a web developer',
  'writes code',
  'is on GitHub',
  'is on Twitter',
  'is on Tumblr',
  'is on Twitch',
  'is on Spotify',
  'is not on Facebook',
  'drives an Asp Explorer',
  'likes racecars',
  'likes aeroplanes',
  'is online',
  'is offline',
  'is tired',
  'is typing',
  "doesn't smoke",
  'plays video games',
  'redesigns this website every other month',
  'plays Elite: Dangerous',
  'has a phone',
  'has a smartwatch',
  'takes photos',
  'has a Raspberry Pi',
  'is afraid of dogs',
  'hates TV',
  'has a Spotify playlist',
  'writes about web development',
  'likes vaporwave',
  'likes learning new stuff',
  'does React',
  'does TypeScript',
  'does JavaScript',
  'does Elixir',
  'does Laravel',
  'does node.js',
  'does PHP. sorry.',
  'listens to music',
  'has a laptop',
  'has a gaming PC',
  'wrote this flavor text',
  'has a keyboard',
  'has internet',
  'sleeps at night',
  'is not a furry',
  'wishes you a good day',
  'probably likes you',
  "thinks you're cool"
]
