const flavors = [
  'is a web developer',
  'writes code',
  'drives an Asp Explorer',
  'likes racing cars',
  'is online',
  'is offline',
  'is typing',
  'doesn\'t smoke',
  'plays video games',
  'has a phone',
  'takes photos',
  'is afraid of dogs',
  'hates TV',
  'likes vaporwave',
  'does React',
  'does TypeScript',
  'does JavaScript',
  'does Laravel',
  'does node.js',
  'listens to music',
  'has a laptop',
  'wrote this flavor text',
  'has an internet connection',
  'sleeps at night',
  'is not a furry',
  'probably likes you'
]

export default flavors
