on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node-gyp (deasync workaround)
        run: npm install -g node-gyp
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Cache built files
        uses: actions/cache@v3
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore built files from cache
        uses: actions/cache@v3
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Lint and typecheck
        run: yarn run validate
        env:
          CI: true
